### ISSUE TITLE
Accuracy goes down to 50%

### ISSUE THREAD

**Issue by kamat900** [nils-wisiol/puf-mlp#1]
Dear Nils Wisiol, 

When I tried to modify your code to run with dataset of asseri (downloads from https://archive.ics.uci.edu/ml/datasets/Physical+Unclonable+Functions). The accuracy of model goes downto 50%. Please give me some advices to improve.
Thank you.
p/s: Here are my code

[python.txt](https://github.com/nils-wisiol/puf-mlp/files/5407435/python.txt)

**Comment by nils-wisiol** [comment]
I was never able to fully reproduce results by Asseri et al, maybe that is the reason. If you let me know what you are trying to do, maybe a LR attack will do?

**Comment by kamat900** [comment]
I am trying to reproduce Asseri et al results. Thank for your answer.

**Comment by nils-wisiol** [comment]
Good luck, please let me know if you have success. I've been told by other research groups that they also failed in reproducing.

**Comment by nils-wisiol** [comment]
You may be interested in https://github.com/kmursi/ML_Attack_XOR_PUF and https://www.mdpi.com/2079-9292/9/10/1715

**Comment by kamat900** [comment]
Thank you so much, I will try it.
